 Streaming</Badge>
             <Badge variant="secondary" className="text-xs">claude-sonnet-4-5</Badge>
                       </div>
                               </div>
                                       <Card className="mb-6">
                                                 <CardHeader className="pb-3">
                                                             <CardTitle className="text-base">Select Patient</CardTitle>
                                                                       </CardHeader>
                                                                                 <CardContent className="space-y-3">
                                                                                             <Select value={selectedId} onValueChange={setSelectedId}>
                                                                                                           <SelectTrigger>
                                                                                                                           <SelectValue placeholder="Select an admitted patient..." />
                                                                                                                                         </SelectTrigger>
                                                                                                                                                       <SelectContent>
                                                                                                                                                                       {admitted.map((inquiry) => (
                                                                                                                                                                                         <SelectItem key={inquiry.id} value={String(inquiry.id)}>
                                                                                                                                                                                                             {inquiry.clientName || inquiry.callerName || `Inquiry #${inquiry.id}`}
                                                                                                                                                                                                                               </SelectItem>
                                                                                                                                                                                                                                               ))}
                                                                                                                                                                                                                                                             </SelectContent>
                                                                                                                                                                                                                                                                         </Select>
                                                                                                                                                                                                                                                                                     <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                   <Button onClick={handleGenerate} disabled={isStreaming || !selectedId} className="flex-1 sm:flex-none">
                                                                                                                                                                                                                                                                                                                   {isStreaming ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</> : <><Brain className="w-4 h-4 mr-2" /> Generate Report</>}
                                                                                                                                                                                                                                                                                                                                 </Button>
                                                                                                                                                                                                                                                                                                                                               {isStreaming && <Button variant="outline" onClick={() => abortRef.current?.abort()}>Stop</Button>}
                                                                                                                                                                                                                                                                                                                                                             {result && !isStreaming && (
                                                                                                                                                                                                                                                                                                                                                                             <Button variant="outline" onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                               const blob = new Blob([result], { type: "text/plain" });
                                                                                                                                                                                                                                                                                                                                                                                                                 const url = URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                                                                                                                                                                   const a = document.createElement("a");
                                                                                                                                                                                                                                                                                                                                                                                                                                                     a.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       a.download = `admissions-report-${selectedId}.txt`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         a.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <Download className="w-4 h-4 mr-2" /> Export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {(result || isStreaming) && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <CardHeader className="pb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <CardTitle className="text-base">Generated Report</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {result ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <pre className="text-sm whitespace-pre-wrap font-mono bg-muted/30 rounded-lg p-4 leading-relaxed overflow-auto max-h-[600px]">{result}</pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div className="min-h-[200px] flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="flex items-center gap-2 text-muted-foreground text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <Loader2 className="w-4 h-4 animate-spin" /> Generating clinical report...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }