import { useState } from "react";
import { useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Search, ArrowLeft, Brain, ChevronRight, Loader2, Sparkles } from "lucide-react";
import type { Inquiry } from "@shared/schema";

export default function AISearch() {
  const [, navigate] = useLocation();
    const [query, setQuery] = useState("");
      const [submitted, setSubmitted] = useState("");

        const { data, isLoading } = useQuery<{ results: Inquiry[]; explanation: string }>({
            queryKey: ["/api/ai/search", submitted],
                enabled: !!submitted,
                  });

                    const handleSearch = (e: React.FormEvent) => {
                        e.preventDefault();
                            if (query.trim()) setSubmitted(query.trim());
                              };

                                return (
                                    <div className="min-h-screen bg-background">
                                          <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                                                  <div className="container mx-auto px-4 py-3 flex items-center gap-3">
                                                            <button onClick={() => navigate("/ai")} className="text-muted-foreground hover:text-foreground transition-colors text-sm flex items-center gap-1">
                                                                        <ArrowLeft className="w-4 h-4" /> AI Features
                                                                                  </button>
                                                                                            <span className="text-muted-foreground">/</span>
                                                                                                      <div className="flex items-center gap-2">
                                                                                                                  <Search className="w-5 h-5 text-primary" />
                                                                                                                              <h1 className="text-xl font-bold">AI Smart Search</h1>
                                                                                                                                        </div>
                                                                                                                                                </div>
                                                                                                                                                      </header>
                                                                                                                                                            <main className="container mx-auto px-4 py-6 max-w-4xl">
                                                                                                                                                                    <div className="mb-6">
                                                                                                                                                                              <div className="flex items-center gap-3 mb-2">
                                                                                                                                                                                          <div className="w-10 h-10 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
                                                                                                                                                                                                        <Sparkles className="w-5 h-5 text-purple-700 dark:text-purple-300" />
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold">Natural Language Search</h2>
                                                                                                                                                                                                                                                            <p className="text-muted-foreground text-sm">Ask anything about your pipeline in plain English</p>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                            <Badge variant="secondary" className="text-xs">claude-haiku-4-5</Badge>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                            <form onSubmit={handleSearch} className="flex gap-2 mb-6">
                                                                                                                                                                                                                                                                                                                      <Input
                                                                                                                                                                                                                                                                                                                                  placeholder="e.g. 'Show me all Blue Cross patients in pre-assessment' or 'Who needs follow-up today?'"
                                                                                                                                                                                                                                                                                                                                              value={query}
                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                      className="flex-1"
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                          <Button type="submit" disabled={isLoading || !query.trim()}>
                                                                                                                                                                                                                                                                                                                                                                                                      {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <><Brain className="w-4 h-4 mr-2" /> Search</>}
                                                                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                          {!submitted && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm font-medium text-muted-foreground">Try asking:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {["Show me all patients in VOB pending", "Who was admitted this month?", "Find inquiries with BlueCross insurance", "Which referral sources sent the most clients?"].map((example) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button key={example} onClick={() => { setQuery(example); setSubmitted(example); }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="block w-full text-left text-sm px-4 py-2 rounded-lg border bg-card hover:bg-muted transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {example}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {isLoading && <div className="space-y-3">{[1, 2, 3].map((i) => <Skeleton key={i} className="h-16 w-full" />)}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {data?.explanation && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Card className="border-purple-200 dark:border-purple-800 bg-purple-50/30 dark:bg-purple-950/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardContent className="pt-4"><p className="text-sm text-muted-foreground">{data.explanation}</p></CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {data?.results?.map((inquiry) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button key={inquiry.id} onClick={() => navigate(`/inquiry/${inquiry.id}`)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full text-left p-4 rounded-lg border bg-card hover:bg-muted transition-colors flex items-center justify-between gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="font-medium">{inquiry.clientName || inquiry.callerName || "Unknown"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-muted-foreground">{inquiry.stage} · {inquiry.insuranceProvider || "No insurance"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ChevronRight className="w-5 h-5 text-muted-foreground flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {data && data.results?.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center py-12 text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Search className="w-12 h-12 mx-auto mb-3 opacity-20" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>No results found for your query.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }