import { useState, useRef, useEffect, useCallback } from "react";
import { useLocation } from "wouter";
import { Search, X, User, Building2, FileText, ClipboardList, CheckSquare, Users } from "lucide-react";
import { Input } from "@/components/ui/input";

interface SearchResult {
  id: number;
    type: "lead" | "contact" | "facility" | "note" | "activity" | "task";
      title: string;
        subtitle?: string;
          url: string;
          }

          interface GlobalSearchResults {
            leads: SearchResult[];
              contacts: SearchResult[];
                facilities: SearchResult[];
                  notes: SearchResult[];
                    activity: SearchResult[];
                      tasks: SearchResult[];
                      }

                      const GROUP_LABELS: Record<string, string> = {
                        leads: "Leads",
                          contacts: "Contacts",
                            facilities: "Facilities",
                              notes: "Notes",
                                activity: "BD Activity",
                                  tasks: "Tasks",
                                  };

                                  const GROUP_ICONS: Record<string, typeof User> = {
                                    leads: User,
                                      contacts: Users,
                                        facilities: Building2,
                                          notes: FileText,
                                            activity: ClipboardList,
                                              tasks: CheckSquare,
                                              };

                                              export function GlobalSearch() {
                                                const [query, setQuery] = useState("");
                                                  const [results, setResults] = useState<GlobalSearchResults | null>(null);
                                                    const [isOpen, setIsOpen] = useState(false);
                                                      const [isLoading, setIsLoading] = useState(false);
                                                        const [, navigate] = useLocation();
                                                          const inputRef = useRef<HTMLInputElement>(null);
                                                            const containerRef = useRef<HTMLDivElement>(null);
                                                              const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

                                                                const fetchResults = useCallback(async (q: string) => {
                                                                    if (!q.trim() || q.trim().length < 2) {
                                                                          setResults(null);
                                                                                setIsLoading(false);
                                                                                      return;
                                                                                          }
                                                                                              setIsLoading(true);
                                                                                                  try {
                                                                                                        const resp = await fetch(`/api/search?q=${encodeURIComponent(q.trim())}`, {
                                                                                                                credentials: "include",
                                                                                                                      });
                                                                                                                            if (resp.ok) {
                                                                                                                                    const data = await resp.json();
                                                                                                                                            setResults(data);
                                                                                                                                                  }
                                                                                                                                                      } catch {
                                                                                                                                                            // silently fail
                                                                                                                                                                } finally {
                                                                                                                                                                      setIsLoading(false);
                                                                                                                                                                          }
                                                                                                                                                                            }, []);

                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                  if (debounceRef.current) clearTimeout(debounceRef.current);
                                                                                                                                                                                      if (!query.trim()) {
                                                                                                                                                                                            setResults(null);
                                                                                                                                                                                                  setIsOpen(false);
                                                                                                                                                                                                        return;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                setIsOpen(true);
                                                                                                                                                                                                                    debounceRef.current = setTimeout(() => {
                                                                                                                                                                                                                          fetchResults(query);
                                                                                                                                                                                                                              }, 300);
                                                                                                                                                                                                                                  return () => {
                                                                                                                                                                                                                                        if (debounceRef.current) clearTimeout(debounceRef.current);
                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                              }, [query, fetchResults]);

                                                                                                                                                                                                                                                // Close dropdown when clicking outside
                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                      const handler = (e: MouseEvent) => {
                                                                                                                                                                                                                                                            if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
                                                                                                                                                                                                                                                                    setIsOpen(false);
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                  document.addEventListener("mousedown", handler);
                                                                                                                                                                                                                                                                                      return () => document.removeEventListener("mousedown", handler);
                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                          const handleSelect = (url: string) => {
                                                                                                                                                                                                                                                                                              setQuery("");
                                                                                                                                                                                                                                                                                                  setResults(null);
                                                                                                                                                                                                                                                                                                      setIsOpen(false);
                                                                                                                                                                                                                                                                                                          navigate(url);
                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                              const clearSearch = () => {
                                                                                                                                                                                                                                                                                                                  setQuery("");
                                                                                                                                                                                                                                                                                                                      setResults(null);
                                                                                                                                                                                                                                                                                                                          setIsOpen(false);
                                                                                                                                                                                                                                                                                                                              inputRef.current?.focus();
                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                  const hasResults = results && Object.values(results).some((arr) => arr.length > 0);
                                                                                                                                                                                                                                                                                                                                    const groupKeys = ["leads", "contacts", "facilities", "notes", "activity", "tasks"] as const;

                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                          <div ref={containerRef} className="relative flex-1 max-w-sm">
                                                                                                                                                                                                                                                                                                                                                <div className="relative">
                                                                                                                                                                                                                                                                                                                                                        <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground pointer-events-none" />
                                                                                                                                                                                                                                                                                                                                                                <Input
                                                                                                                                                                                                                                                                                                                                                                          ref={inputRef}
                                                                                                                                                                                                                                                                                                                                                                                    value={query}
                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                        onFocus={() => query.trim().length >= 2 && setIsOpen(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Search leads, contacts, facilities, notes, activity..."
                                                                                                                                                                                                                                                                                                                                                                                                                            className="pl-8 pr-8 h-9 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                      data-testid="input-global-search"
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {query && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={clearSearch}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <X className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isOpen && query.trim().length >= 2 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="absolute top-full left-0 right-0 mt-1 bg-popover border rounded-lg shadow-lg z-50 max-h-[480px] overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isLoading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="px-4 py-3 text-sm text-muted-foreground">Searching...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!isLoading && !hasResults && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="px-4 py-3 text-sm text-muted-foreground">No results found</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!isLoading && hasResults && groupKeys.map((key) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const group = results![key];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!group || group.length === 0) return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const Icon = GROUP_ICONS[key];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={key}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 px-3 pt-3 pb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Icon className="w-3.5 h-3.5 text-muted-foreground" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {GROUP_LABELS[key]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {group.slice(0, 5).map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={`${key}-${item.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full text-left px-4 py-2 hover:bg-accent transition-colors flex flex-col gap-0.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => handleSelect(item.url)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-sm font-medium truncate">{item.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {item.subtitle && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-muted-foreground truncate">{item.subtitle}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }